language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
before_install:
- openssl aes-256-cbc -K $encrypted_aca36f303415_key -iv $encrypted_aca36f303415_iv
  -in aws.yml.enc -out aws.yml -d
- chmod +x gradlew

# 1
before_deploy:
  - zip -r Server * # 2
  - mkdir -p deploy  # 3
  - mv Server.zip deploy/Server.zip # 4

# 5
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: bcde-bucket    # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # 6
    wait-until-deployed: true
  on: # 7
    all_branches: true


notifications:
  email:
    recipients:
    - ohk9134@naver.com


