language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
before_install:
- openssl aes-256-cbc -K $encrypted_aca36f303415_key -iv $encrypted_aca36f303415_iv
  -in aws.yml.enc -out aws.yml -d
- chmod +x gradlew
notifications:
  email:
    recipients:
    - ohk9134@naver.com
