language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --stacktrace"
before_install:
- openssl aes-256-cbc -K $encrypted_687a5032d38a_key -iv $encrypted_687a5032d38a_iv
  -in aws-test.yml.enc -out aws-test.yml -d
- openssl aes-256-cbc -K $encrypted_aca36f303415_key -iv $encrypted_aca36f303415_iv
  -in aws.yml.enc -out aws.yml -d
- chmod +x gradlew
before_deploy:
- zip -r Server *
- mkdir -p deploy
- mv Server.zip deploy/Server.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: bcde-bucket
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
notifications:
  email:
    recipients:
    - ohk9134@naver.com
