spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/bc'de?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username : root
    password : root

  data:
    web:
      pageable:
        default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  servlet:
    multipart:
      max-request-size: 5MB  #업로드 파일 크기 총량 제한
      max-file-size: 2MB     #업로드 파일 크기 제한

  profiles:
    include: jwt

  jpa:
    show-sql : true
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        format_sql : true
        show_sql : true

        default_batch_fetch_size: 500 #배치 사이즈 (Collection 조회 최적화)

      open-in-view : false

logging:
  level:
    org:

      hiberante:
        SQL: debug

    com:
      bcdeproject : info

image:
  dir: D:\bcdeImg\
