# 공통
spring:
  config:
    activate:
      on-profile: "common"


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

logging:
  level:
    org:
      hiberante:
        SQL: debug

    com:
      bcdeproject : info


