# 공통
spring:
  config:
    activate:
      on-profile: "common"
    servlet:
      multipart:
        max-request-size: 20MB  #업로드 파일 크기 총량 제한
        max-file-size: 2MB     #업로드 파일 크기 제한


  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

logging:
  level:
    org:
      hiberante:
        SQL: debug

    com:
      bcdeproject : info


