spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://bcde-rds-instance.c2xonyrh3m6y.ap-northeast-2.rds.amazonaws.com:3306/bcde_test?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username : admin
    password : bcdetest

  data:
    web:
      pageable:
        default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher

  profiles:
    include: jwt, local

  jpa:
    show-sql : true
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        format_sql : true
        show_sql : true

        default_batch_fetch_size: 500 #배치 사이즈 (Collection 조회 최적화)

      open-in-view : false

logging:
  level:
    org:

      hiberante:
        SQL: debug

    com:
      bcdeproject : info
      amazonaws:
        util:
          EC2MetadataUtils: error

image:
  dir: D:\bcdeImg\

---
### AWS S3 설정
spring:
  group:
    "local": "local, common"
    "development": "development, common"
  active: local

---
# 공통
spring:
  config:
    activate:
      on-profile: "common"
    servlet:
      multipart:
        max-request-size: 20MB  #업로드 파일 크기 총량 제한
        max-file-size: 2MB     #업로드 파일 크기 제한

---
# AWS S3에 필요한 정보
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: bcde-bucket
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
# 로컬 환경
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/static/files/

---
# 배포 환경
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /home/ec2-user/files/